from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
                  path('', views.custom_login, name='login_view'),
                  path('login/', views.custom_login, name='login_view'),
                  path('logout/', views.logout_view, name='logout'),
                  path('index/', views.index, name='index'),
                  path('footer/', views.footer, name='footer'),
                  path('head/', views.head, name='head'),
                  path('header/', views.header, name='header'),
                  path('navheader_view/', views.navheader_view, name='navheader_view'),
                  path('sidebar/', views.index, name='sidebar'),
                  path('app_calender/', views.app_calender, name='app_calender'),
                  path('contact/', views.contact, name='contact'),
                  path('performance/', views.performance, name='performance'),
                  path('task/', views.task, name='task'),
                  path('add_master_category/', views.add_category, name='add_category'),
                  path('category_list/', views.category_list, name='category_list'),
                  path('update_category/<int:category_id>/', views.update_category, name='update_category'),
                  path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
                  path('sub_category/<int:category_id>/', views.subcategory_list, name='subcategory_list'),
                  path('get_category_dropdown/<int:category_id>/', views.get_category_dropdown,
                       name='get_category_dropdown'),
                  path('subcategory_list/', views.subcategory_list, name='subcategory_list'),
                  path('category_dropdown/', views.category_dropdown, name='category_dropdown'),
                  path('update_subcategory/<int:id>/', views.update_subcategory, name='update_subcategory'),
                  path('add_user/', views.add_user, name='add_user'),
                  path('user_list/', views.user_list, name='user_list'),
                  path('update_user/<int:user_id>/', views.update_user, name='update_user'),
                  path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
                  path('employee/', views.employee, name='employee'),
                  path('add_employee/', views.add_employee, name='add_employee'),
                  path('employee_dropdown/', views.employee_dropdown, name='employee_dropdown'),
                  path('employee_list/', views.employee_list, name='employee_list'),
                  path('add_equipment/', views.add_equipment, name='add_equipment'),
                  path('equipment_list/', views.equipment_list, name='equipment_list'),
                  path('equipment_list/<int:subcategory_id>/', views.equipment_list, name='equipment_list'),
                  path('edit_subcategory_dropdown/', views.edit_subcategory_dropdown, name='edit_subcategory_dropdown'),
                  path('edit_get_category_name/', views.edit_get_category_name, name='edit_get_category_name'),
                  path('fetch_stock_status/<int:equipment_id>/', views.fetch_stock_status, name='fetch_stock_status'),
                  path('fetch_serial_barcode_no/<int:equipment_id>/', views.fetch_serial_barcode_no,
                       name='fetch_serial_barcode_no'),
                  path('get_dimension_list/<int:equipment_id>/', views.get_dimension_list, name='get_dimension_list'),
                  path('insert_vendor/', views.insert_vendor, name='insert_vendor'),
                  path('subcategory_dropdown/', views.subcategory_dropdown, name='subcategory_dropdown'),
                  path('get_category_name/', views.get_category_name, name='get_category_name'),
                  path('Stock_list/', views.stock_list, name='Stock_list'),
                  path('fetch-equipment-list/', views.fetch_stock_equipment_list, name='fetch_stock_equipment_list'),
                  path('stock-in/<int:equipment_id>/', views.stock_in, name='stock_in'),
                  path('update-stock-in/<int:row_id>/', views.update_stock_in, name='update-stock-in'),
                  path('fetch_stock_details_by_name/', views.fetch_stock_details_by_name,
                       name='fetch_stock_details_by_name'),
                  path('add_event_view/', views.add_event_view, name='add_event_view'),
                  path('get_eventvalue/', views.get_eventvalue, name='get_eventvalue'),
                  path('modify_employee/', views.modify_employee, name='modify_employee'),
                  path('delete_attachment/', views.delete_attachment, name='delete_attachment'),
                  path('add_job/', views.add_job, name='add_job'),
                  path('fetch_client_name/', views.fetch_client_name, name='fetch_client_name'),
                  path('fetch_venue_address/', views.fetch_venue_address, name='fetch_venue_address'),
                  path('fetch_venue_name/', views.fetch_venue_name, name='fetch_venue_name'),
                  path('get_new_row_data/', views.get_new_row_data, name='get_new_row_data'),
                  path('fetch_master_categories/', views.fetch_master_categories, name='fetch_master_categories'),
                  path('fetch_equipment_names/', views.fetch_equipment_names, name='fetch_equipment_names'),
                  path('check_equipment_in_temp/', views.check_equipment_in_temp, name='check_equipment_in_temp'),
                  path('fetch_rental_price/', views.fetch_rental_price, name='fetch_rental_price'),
                  path('save_row_data/', views.insert_data, name='save_row_data'),
                  path('get_employee_name/', views.get_employee_name, name='get_employee_name'),
                  path('delete_row_from_temp_table/', views.delete_row_from_temp_table,
                       name='delete_row_from_temp_table'),
                  path('jobs_list/', views.jobs_list, name='jobs_list'),
                  path('get_status_counts/', views.get_status_counts, name='get_status_counts'),
                  path('update_jobs/<int:id>/', views.update_jobs, name='update_jobs'),
                  path('delete_jobs/<int:id>/', views.delete_jobs, name='delete_jobs'),
                  path('add_connects/', views.add_connects, name='add_connects'),
                  path('connect_list/', views.connect_list, name='connect_list'),
                  path('company_dropdown_view/', views.company_dropdown_view, name='company_dropdown_view'),
                  path('update_connect/<int:id>/', views.update_connect, name='update_connect'),
                  path('delete_connect/<int:id>/', views.delete_connect, name='delete_connect'),
                  path('job_details/', views.job_details_page, name='job_details_page'),
                  path('get_job_details/', views.get_job_details, name='get_job_details'),
                  path('update_job_detail/<int:id>/', views.update_job_details, name='update_job_detail'),
                  path('save_new_row/', views.save_new_row, name='save_new_row'),
                  path('delete_job_row/<int:job_id>/', views.delete_job_row, name='delete_job_row'),
                  path('warehouse_master/', views.warehouse_master, name='warehouse_master'),
                  path('company_master/', views.company_master, name='company_master'),
                  path('company_master_list/', views.company_master_list, name='company_master_list'),
                  path('company_name_dropdown/', views.company_name_dropdown, name='company_name_dropdown'),
                  path('delete_company_master/<int:id>/', views.delete_company_master, name='delete_company_master'),
                  path('add_warehouse_master/', views.add_warehouse_master, name='add_warehouse_master'),
                  path('warehouse_master_list/', views.warehouse_master_list, name='warehouse_master_list'),
                  path('delete_warehouse_master/<int:id>/', views.delete_warehouse_master,
                       name='delete_warehouse_master'),
                  path('update_warehouse/<int:id>/', views.update_warehouse, name='update_warehouse'),
                  path('update_company/<int:id>/', views.update_company, name='update_company'),
                  path('fetch_subcategory_name/<int:subcategory_id>/', views.fetch_subcategory_name,
                       name='fetch_subcategory_name'),
                  path('fetch_subcategory_type/<int:subcategory_id>/', views.fetch_subcategory_type,
                       name='fetch_subcategory_type'),
                  path('get_category_type/', views.get_category_type, name='get_category_type'),
                  path('fetch_stock_details/', views.fetch_stock_details, name='fetch_stock_details'),
                  path('fetch_client_contact_number/', views.fetch_client_contact_number,
                       name='fetch_client_contact_number'),
                  path('print_jobs/', views.print_jobs, name='print_jobs'),
                  path('check_stock_availability/', views.check_stock_availability, name='check_stock_availability'),
                  path('update_all_job_details/', views.update_all_job_details, name='update_all_job_details'),
                  path('save_job_details/', views.save_job_details, name='save_job_details'),
                  path('delete_job_detail/', views.delete_job_detail, name='delete_job_detail'),
                  path('fetch-events/', views.fetch_events, name='fetch-events'),
                  path('job_form/', views.job_form, name='job_form'),
                  path('add_job_test/', views.add_job_test, name='add_job_test'),
                  path('search-equipment/', views.search_equipment, name='search_equipment'),
                  path('fetch-equipment-with-barcodes/', views.fetch_equipment_with_barcodes,
                       name='fetch_equipment_with_barcodes'),
                  path('search-crew/', views.search_crew, name='search_crew'),
                  path('subcategorytest-list/', views.subcategorytest_list, name='subcategorytest_list'),
                  path('fetch-categories/', views.fetch_categories, name='fetch_categories'),
                  path('add_subcategory/', views.add_subcategory, name='add_subcategory'),
                  path('delete_subcategory/<int:subcategory_id>/', views.delete_subcategory, name='delete_subcategory'),
                  path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
                  path('update_master_category/<int:category_id>/', views.update_master_category,
                       name='update_master_category'),
                  path('update_sub_category/<int:subcategory_id>/', views.update_sub_category,
                       name='update_sub_category'),
                  path('get-sub-categories/', views.get_sub_categories, name='get_sub_categories'),
                  path('submit_equipment/', views.submit_equipment, name='submit_equipment'),
                  path('fetch_equipment_list/', views.fetch_equipment_list, name='fetch_equipment_list'),
                  path('delete_equipment/<int:equipment_id>/', views.delete_equipment, name='delete_equipment'),
                  path('fetch_equipment_details/', views.fetch_equipment_details, name='fetch_equipment_details'),
                  path('update_equipment/', views.update_equipment, name='update_equipment'),
                  path('insert_stock_details/', views.insert_stock_details, name='insert_stock_details'),
                  path('equipment_by_category/', views.equipment_by_category, name='equipment_by_category'),
                  path('get_categories/', views.get_categories, name='get_categories'),
                  path('stock_details_view/<int:equipment_id>/', views.stock_details_view, name='stock_details_view'),
                  path('update_stock_details/', views.update_stock_details, name='update_stock_details'),
                  path('fetch_job_list/', views.fetch_job_list, name='fetch_job_list'),
                  path('insert-crew-allocation/', views.insert_crew_allocation, name='insert-crew-allocation'),
                  path('insert-transportation-data/', views.insert_transportation_data,
                       name='insert_transportation_data'),
                  path('insert-sub-vendor-details/', views.insert_sub_vendor_details, name='insert_sub_vendor_details'),
                  path('fetch-all-subcategories/', views.fetch_all_subcategories, name='fetch_all_subcategories'),
                  path('equipment_by_category/', views.equipment_by_category, name='equipment_by_category'),
                  path('get_equipment_details/<int:equipment_id>/', views.get_equipment_details,
                       name='get_equipment_details'),
                  path('get_serial_details/<int:equipment_id>/', views.get_serial_details, name='get_serial_details'),
                  path('get_stock_details/<int:equipment_id>/', views.get_stock_details, name='get_stock_details'),
                  path('add_row/', views.add_row, name='add_row'),
                  path('fetch_company_data/', views.fetch_company_data, name='fetch_company_data'),
                  path('fetch_venue_data/', views.fetch_venue_data, name='fetch_venue_data'),
                  path('fetch_individual_data/', views.fetch_individual_data, name='fetch_individual_data'),
                  path('fetch_company_names/', views.fetch_company_names, name='fetch_company_names'),
                  path('delete_data/', views.delete_data, name='delete_data'),
                  path('update_company_data/', views.update_company_data, name='update_company_data'),
                  path('update-venue-data/', views.update_venue_data, name='update_venue_data'),
                  path('update-individual-data/', views.update_individual_data, name='update_individual_data'),
                  path('fetch_individual_names/', views.fetch_individual_names, name='fetch_individual_names'),
                  path('insert-temp-data/', views.insert_temp_data, name='insert_temp_data'),
                  path('search-equipment/', views.search_equipment, name='search_equipment'),
                  path('fetch-all-subcategories/', views.fetch_all_subcategories, name='fetch_all_subcategories'),
                  path('fetch-equipment-with-barcodes/', views.fetch_equipment_with_barcodes,
                       name='fetch_equipment_with_barcodes'),
                  path('insert-sub-vendor-details/', views.insert_sub_vendor_details, name='insert_sub_vendor_details'),
                  path('search-employee/', views.search_employee, name='search_employee'),
                  path('insert-crew-allocation/', views.insert_crew_allocation, name='insert-crew-allocation'),
                  path('delete-crew-allocation/', views.delete_crew_allocation, name='delete_crew_allocation'),
                  path('insert_transportation/', views.insert_transportation, name='insert_transportation'),
                  path('get_temp_details/<int:jobId>/', views.get_temp_details, name='get_temp_details'),
                  path('update_temp_details/<str:jobId>/', views.update_temp_details, name='update_temp_details'),
                  path('calculate-total-amount/<int:job_id>/', views.calculate_total_amount,
                       name='calculate_total_amount'),
                  path('fetch-equipment-details/<int:job_id>/', views.fetch_edit_equipment_details,
                       name='fetch_edit_equipment_details'),
                  path('update-equipment-quantity/', views.update_equipment_quantity, name='update_equipment_quantity'),
                  path('fetch-sub-vendor-details/<int:job_id>/', views.fetch_sub_vendor_details,
                       name='fetch_sub_vendor_details'),
                  path('update-sub-vendor-details/', views.update_sub_vendor_details, name='update_sub_vendor_details'),
                  path('delete-sub-vendor/<int:id>/', views.delete_sub_vendor, name='delete_sub_vendor'),
                  path('fetch_crew_allocation/', views.fetch_crew_allocation, name='fetch_crew_allocation'),
                  path('delete_crew_allocation/<int:id>/', views.delete_crew_allocation, name='delete_crew_allocation'),
                  path('get_transportation_allocation/', views.get_transportation_allocation,
                       name='get_transportation_allocation'),
                  path('delete_transportation_allocation/', views.delete_transportation_allocation,
                       name='delete_transportation_allocation'),
                  path('update_transportation_allocation/', views.update_transportation_allocation,
                       name='update_transportation_allocation'),
                  path('insert_transportation/', views.insert_transportation, name='insert_transportation'),
                  path('edit_job/<int:jobId>/', views.edit_job, name='edit_job'),
                  path('update-total-amount-details/<int:job_id>/', views.update_total_amount_details,
                       name='update_total_amount_details'),
                  path('fetch-crew-allocation/', views.fetch_crew_allocation, name='fetch_crew_allocation'),
                  path('job_addition/', views.job_addition, name='job_addition'),
                  path('fetch-equipment-details/<int:job_id>/', views.fetch_edit_equipment_details,
                       name='fetch_edit_equipment_details'),
                  path('fetch-sub-vendor-details/<int:job_id>/', views.fetch_sub_vendor_details,
                       name='fetch_sub_vendor_details'),
                  path('fetch-crew-allocation-details/<int:job_id>/', views.fetch_crew_allocation_details,
                       name='fetch_crew_allocation_details'),
                  path('update-transportation-details/<int:job_id>/', views.update_transportation_details,
                       name='update_transportation_details'),
                  path('calculate-total-amount/<int:job_id>/', views.calculate_total_amount,
                       name='calculate_total_amount'),
                  path('get_transportation_allocation/', views.get_transportation_allocation,
                       name='get_transportation_allocation'),
                  path('update_transportation_allocation/', views.update_transportation_allocation,
                       name='update_transportation_allocation'),
                  path('delete_transportation_allocation/', views.delete_transportation_allocation,
                       name='delete_transportation_allocation'),
                  path('fetch-crew-allocation/', views.fetch_crew_allocation, name='fetch_crew_allocation'),
                  path('fetch-inserted-row/', views.fetch_inserted_row, name='fetch_inserted_row'),
                  path('update-quantity/', views.update_quantity, name='update_quantity'),
                  path('fetch_employee_names/', views.fetch_employee_names, name='fetch_employee_names'),
                  path('fetch-job-reference-no/', views.fetch_job_reference_no, name='fetch_job_reference_no'),
                  path('fetch-equipment-data/', views.fetch_equipment_data, name='fetch_equipment_data'),
                  path('insert-equipment-details/', views.insert_equipment_details_test,
                       name='insert_equipment_details_test'),
                  path('fetch-equipment-details-multiple/', views.fetch_equipment_details_multiple,
                       name='fetch_equipment_details_multiple'),
                  path('fetch-employee-names/', views.fetch_employee_names_equipment,
                       name='fetch_employee_names_equipment'),
                  path('delete-equipment-id/', views.delete_equipment_id, name='delete_equipment_id'),
                  path('update-equipment-id/', views.update_equipment_id, name='update_equipment_id'),
                  path('insert-equipment-details-id/', views.insert_equipment_details_id,
                       name='insert_equipment_details_id'),
                  path('save_crew_allocation/', views.save_crew_allocation, name='save_crew_allocation'),
                  path('delete_crew_allocation_row/', views.delete_crew_allocation_row,
                       name='delete_crew_allocation_row'),
                  path('update-crew-allocation-row/', views.update_crew_allocation_row,
                       name='update_crew_allocation_row'),
                  path('fetch-equipment-detail-id/', views.fetch_equipment_detail_id, name='fetch_equipment_detail_id'),
                  path('fetch-crew-allocation-edit/', views.fetch_crew_allocation_edit,
                       name='fetch_crew_allocation_edit'),
                  path('search-employee-crew/', views.search_employee_crew, name='search_employee_crew'),
                  path('save_crew_delivery_allocation/', views.save_crew_delivery_allocation,
                       name='save_crew_delivery_allocation'),
                  path('update-crew-allocation-delivery/', views.update_crew_allocation_delivery,
                       name='update_crew_allocation_delivery'),
                  path('fetch-temp-crew-details/', views.fetch_temp_crew_details, name='fetch_temp_crew_details'),
                  # 12/12/2024
                  path('fetch-equipment-composite/', views.fetch_equipment_composite, name='fetch_equipment_composite'),
                  path('save_composite_rack/', views.save_composite_rack, name='save_composite_rack'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
